- hosts: "{{ host_or_group }}"
  vars_files:
    - ./vars/main.yml
  tasks: 
    - name: Read in the vault
      ansible.builtin.include_vars:
        file: "{{ vsts_agent_vaulted_variables }}"
        name: vsts_agent
    - ansible.builtin.include_role:
        name: jamesjonesconsulting.azuredevops_agent_fixes.agent_setup
      vars:
        vsts_agents: "{{ vsts_host_agents }}"
        vsts_agent_podman_group: "{{ vsts_agent_host_podman_group }}"
        vsts_agent_url: "{{ vsts_agent_host_url }}"
    #     vsts_agent_registration_token: "{{ vsts_agent_registration_token }}"
    #     vsts_agent_tags: "{{ vsts_agent_host_tags }}"
